function out1 = Jacobian_A(t,in2,in3,d)
%JACOBIAN_A
%    OUT1 = JACOBIAN_A(T,IN2,IN3,D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Aug-2018 15:23:46

K3 = in3(3,:);
K4 = in3(4,:);
K7 = in3(7,:);
K8 = in3(8,:);
K9 = in3(9,:);
K10 = in3(10,:);
K11 = in3(11,:);
K12 = in3(12,:);
K13 = in3(13,:);
K14 = in3(14,:);
X1 = in2(1,:);
X2 = in2(2,:);
X3 = in2(3,:);
t2 = K4+X1;
t3 = K8+X2;
t4 = X3-1.0;
t5 = K12-X3+1.0;
t6 = 1.0./t5;
t7 = K14-X3+1.0;
t8 = 1.0./t7;
t9 = K10+X3;
out1 = reshape([-(K3.*d)./t2+K3.*X1.*d.*1.0./t2.^2,0.0,-K11.*t4.*t6,0.0,-(K7.*d)./t3+K7.*X2.*d.*1.0./t3.^2,-K13.*t4.*t8,0.0,0.0,-K11.*X1.*t6-K13.*X2.*t8-(K9.*d)./t9+K9.*X3.*d.*1.0./t9.^2-K11.*X1.*t4.*1.0./t5.^2-K13.*X2.*t4.*1.0./t7.^2],[3,3]);
