function out1 = Jacobian_B(t,in2,in3,d)
%JACOBIAN_B
%    OUT1 = JACOBIAN_B(T,IN2,IN3,D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Aug-2018 15:23:46

K1 = in3(1,:);
K2 = in3(2,:);
K5 = in3(5,:);
K6 = in3(6,:);
X1 = in2(1,:);
X2 = in2(2,:);
t2 = K2-X1+1.0;
t3 = K6-X2+1.0;
out1 = reshape([-K1./t2-K1.*1.0./t2.^2.*(X1-1.0),0.0,0.0,0.0,-K5./t3-K5.*1.0./t3.^2.*(X2-1.0),0.0,0.0,0.0,0.0],[3,3]);
