function tmp_ODE_B = tmp_ODE_BB(t,in2,in3,d)
%TMP_ODE_BB
%    TMP_ODE_B = TMP_ODE_BB(T,IN2,IN3,D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    01-Aug-2018 15:23:46

K1 = in3(1,:);
K2 = in3(2,:);
K5 = in3(5,:);
K6 = in3(6,:);
X1 = in2(1,:);
X2 = in2(2,:);
tmp_ODE_B = [-(K1.*(X1-1.0))./(K2-X1+1.0);-(K5.*(X2-1.0))./(K6-X2+1.0);0.0];
